1단계 미션 제출합니다.
Meet-Coder-Study/java-baseball pull request #5
Opened 2024-05-23 20:22 UTC by EunjiShin

[여기](https://github.com/EunjiShin/java-baseball/blob/step1/docs/requirements.md)에 기능 요구사항 & 입출력 요구사항 간단하게 정리해두었습니다! 

- 고민되는 점
  - 정답이 매번 랜덤하게 생성된다는 것을 테스트코드로 어떻게 증명할 수 있을지 잘 모르겠습니다. 
    - 반복문을 이용하는 방법을 생각해보았으나, 무한하게 반복하며 체크할 순 없으니 유효하지 않은 테스트인 것 같습니다.
    - 일단은 suffle 메서드가 잘 동작할 것이라 믿고 테스트를 패스했는데, 혹시 다른 방법이 있을까요?
  - 알파벳 & 특수문자를 입력할 수 없다는 것을 테스트하는 방법을 개선하고 싶습니다.
    - 지금은 알파벳과 특수문자를 전부 입력하고 반복을 돌며 체크하는 방식으로 구현했습니다.
    - 알파벳은 a-z, A-Z라서 비교적 간단하게 구현했으나, 특수문자의 경우 가지수가 너무 많아서 (기본 특수문자, 이모지 등등) 모든 케이스를 테스트하지 못하고 있습니다.

2024-05-24 01:36 UTC, ksy90101 requested changes
간단한 피드백을 남겼습니다.
학습의 목적인지 핵사고날을 쓰셨군요 ㅎㅎ
핵사고날을 쓰셨을때 장점이 있었을까요?
지금같은 경우에는 좀 복잡했을거 같은데 ㅎㅎ
한번 수정하시고 요청주세요~

2024-05-24 01:36 UTC, ksy90101 commented on java-baseball-meetcoder/src/main/java/org/example/adapter/enums/Menu.java
> +        }
2depth인거 같은데
Stream으로 변경해보면 어떨까요?
아울러 values()는 매번 생성하다보니 메모리 이슈가 있을거 같아요.
https://rutgo-letsgo.tistory.com/entry/%EB%B2%88%EC%97%AD-Memory-Hogging-Enumvalues-Method%EB%A9%94%EB%AA%A8%EB%A6%AC%EB%A5%BC-%EA%B3%BC%EB%8F%84%ED%95%98%EA%B2%8C-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94-Enumvalues-%EB%A9%94%EC%84%9C%EB%93%9C

위 글을 한번 읽어보면 어떨까요?

2024-05-24 01:36 UTC, ksy90101 commented on java-baseball-meetcoder/src/main/java/org/example/common/config/DiContainter.java
> +public class DiContainter {
👍

2024-05-24 01:36 UTC, ksy90101 commented on java-baseball-meetcoder/src/main/java/org/example/domain/Answer.java
> +        }
validate을 분리하여 작성해보면 어떨까요?
각 validate이 어떤 의미인지 나타내보면 좋을거 같습니다.

2024-05-24 01:36 UTC, ksy90101 commented on java-baseball-meetcoder/src/main/java/org/example/domain/Answer.java
> +    List<Integer> values
숫자에대한 ValueObject를 만들어 보 어떨까요?
1~9사이의 숫자인지 등등 체크해볼수 있을거 같아요~

2024-05-24 01:36 UTC, ksy90101 commented on java-baseball-meetcoder/src/main/java/org/example/domain/InputNumber.java
> +public record InputNumber(
위의 Answers와 분리하셨던데, 두개가 is a 관계가 아닐까요?
이렇게 분리할꺼면 차라리 상속구조로 해보면 어떨까요?

2024-05-24 01:36 UTC, ksy90101 commented on java-baseball-meetcoder/src/main/java/org/example/domain/Result.java
> +        return !Objects.equals(computerNum, userNum) && computerValues.contains(userNum);
아래 isStrik와 중복이 조금 보이는데
차라리 !isStrike && computerValues.contains(userNum)이라고 하는게 . 더좋지 않을까요?

2024-05-24 01:36 UTC, ksy90101 commented on java-baseball-meetcoder/src/test/java/org/example/adapter/enums/MenuTest.java
> +class MenuTest {
ParameterzeidTest를 통해 from에 대한 성공하는 테스트를 작성해보면 어떨까요?
또한 checkQuit도 성공 테스트가 필요하지 않을까요?

2024-05-24 01:36 UTC, ksy90101 commented on java-baseball-meetcoder/src/main/java/org/example/application/service/ResultService.java
> +    public Result check(final Answer answer, final InputNumber inputNumber) {
이 부분에 대한 테스트 코드가 부족하네요 ㅠㅠ

2024-05-24 01:37 UTC, ksy90101 commented
1. 정답이 매번 랜덤하게 생성된다는 것을 테스트코드로 어떻게 증명할 수 있을지 잘 모르겠습니다.
전 굳이 해야 하나 생각합니다. 어떻게 보면 우리는 Java API를 믿고 가는거이기 떄문에 랜덤이라는것을 체크해야 할지 의문이에요.
그래서 가장 중요한건 중복되지 않은 값  및 3개의 숫자가 잘 나오는지 정책만 체크해보면 되지 않을까요?

2. 알파벳 & 특수문자를 입력할 수 없다는 것을 테스트하는 방법을 개선하고 싶습니다.
정규표현식 쓰시면 되지 않을까요 ㅎㅎ

2024-05-24 14:50 UTC, EunjiShin commented on java-baseball-meetcoder/src/main/java/org/example/domain/Result.java
> +        return !Objects.equals(computerNum, userNum) && computerValues.contains(userNum);
오 훨씬 간단해지고 스트라이크와 뭐가 다른지도 한 눈에 보이네요 👍 감사합니다!

2024-05-24 14:50 UTC, EunjiShin commented on java-baseball-meetcoder/src/main/java/org/example/application/service/ResultService.java
> +    public Result check(final Answer answer, final InputNumber inputNumber) {
오악 추가하겠습니다!! ㅠㅠ

2024-05-24 14:59 UTC, EunjiShin commented
@ksy90101 

리뷰 감사합니다! 👍 반영하고 다시 태그 드릴게요 ㅎㅎ!

> 학습의 목적인지 핵사고날을 쓰셨군요 ㅎㅎ 핵사고날을 쓰셨을때 장점이 있었을까요?

이번 미션에선 아래 두 가지 목적으로 핵사고날을 사용했습니다!

1. 미션 2, 3, 4단계에서 어떤 요구사항이 생길지 모르니, 최대한 유연한 구조를 만들고 싶었습니다.
2. 구현보다 추상화에 집중하며 코드를 짜는 연습을 해보고 싶었습니다. 

말씀 주신 것처럼, 1단계에선 오히려 구조가 복잡해지는 느낌이라 이렇다할 장점은 없었던 것 같아요 😂
헥사고날 아키텍처에 익숙해지니 가시적으로 패키지를 관리하기 좋다 정도..?!
남은 미션 진행하면서 생각했던 것처럼 아키텍처 단에서 확장성이 좋은지 차차 확인해보려고 합니다!

2024-05-27 12:32 UTC, ksy90101 approved these changes
고생하셨습니다~
간단한 피드백은 다음 단계에서 살펴보시고 적용하셔도 될거 같아요!
2단계 홧팅입니다!

2024-05-27 12:32 UTC, ksy90101 commented on java-baseball-meetcoder/src/main/java/org/example/MainApplication.java
> +}
NOF를 통일하면 어떨까요?

2024-05-27 12:32 UTC, ksy90101 commented on java-baseball-meetcoder/src/main/java/org/example/adapter/enums/Menu.java
> +    private final String value;
int로 하면 어떨까요?

2024-05-27 12:32 UTC, ksy90101 commented on java-baseball-meetcoder/src/main/java/org/example/adapter/enums/Menu.java
> +        return menu;
optional로 해서 orElseThrow를 해도 깔끔할거 같아요~

2024-05-27 12:32 UTC, ksy90101 commented on java-baseball-meetcoder/src/main/java/org/example/application/service/AnswerService.java
> +    }
매번 만들기 보단 캐싱하면 어떨까요?

2024-05-27 12:32 UTC, ksy90101 commented on java-baseball-meetcoder/src/main/java/org/example/domain/Result.java
> +    }
static을 쓰지 않고 할수 없을까요?
이런 경우 static을 쓰면 어떤 문제가 있을까요...?

2024-05-27 12:32 UTC, merged